POST http://localhost:5000/api/signup HTTP/1.1
Content-Type: application/json

{
    "firstName":"TranThe",
    "lastName":"Hong",
    "email":"trant2he23hong2122w112@gmail.com",
    "password":"admi3n123421"
}
###
POST http://localhost:5000/api/signin HTTP/1.1
content-type: application/json

{
    "firstName":"TranThe",
    "lastName":"Hong",
    "email":"tranthehong1w112@gmail.com",
    "password":"admin12341"
}