POST http://localhost:5000/api/signup HTTP/1.1
Content-Type: application/json

{
    "firstName":"ss",
    "lastName":"Hong",
    "email":"trwew12w3e1rail.com",
    "password":"adms1"
}
###
POST http://localhost:5000/api/signin HTTP/1.1
content-type: application/json

{
    "firstName":"TranThe",
    "lastName":"Hong",
    "email":"trwew123e1rail@gmail.com",
    "password":"adms1"
}